//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.14 at 09:16:57 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://aakash.com/employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.aakash.employee;
